name: CD - Push to Amazon ECR

on: 
  workflow_run:
    workflows: ["CI Docker Build and Push"]
    types: 
      - completed

jobs: 
  deploy: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repo 
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, Push to ECR
        run: |
          Image_URI=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
          docker build -t $Image_URI ./hello_flask 
          docker push $Image_URI

      
