name: CI Docker Build and Push 

on: 
  push:
    # branches: 
    #   - 'master'

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./hello_flask #everything in here is needed 
          file: ./hello_flask/Dockerfile #tells where to find dockerfile
          push: true #this means that once image is built it will be pushed to registery (dockdrhub/aws). If it was false then image would be built and pushed to actions on gihthub but not to registerys
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cicd-workflow:latest
